apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    run: api
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: public
  selector:
    run: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      run: api
  replicas: 1
  template:
    metadata:
      labels:
        run: api
    spec:
      containers:
      - name: api
        image: anrop/anrop-api
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: mysql
                key: database
          - name: MYSQL_HOST
            valueFrom:
              secretKeyRef:
                name: mysql
                key: host
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql
                key: password
          - name: MYSQL_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysql
                key: username
          - name: NEW_RELIC_APP_NAME
            value: api.anrop.se
          - name: NEW_RELIC_LICENSE_KEY
            valueFrom:
              secretKeyRef:
                name: newrelic
                key: licenseKey
          - name: PORT
            value: '8080'
          - name: RACK_ENV
            value: production
          - name: RAILS_ENV
            value: production
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: rails
                key: secretKeyBase
        ports:
          - containerPort: 8080
      restartPolicy: Always
