apiVersion: v1
kind: Service
metadata:
  name: streams
  labels:
    run: streams
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: public
  selector:
    run: streams
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streams
spec:
  selector:
    matchLabels:
      run: streams
  replicas: 1
  template:
    metadata:
      labels:
        run: streams
    spec:
      containers:
      - name: streams
        image: anrop/anrop-streams
        env:
          - name: AVATAR_BASE_URL
            value: https://www.anrop.se/images/avatars/
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: mysql
                key: url
          - name: PORT
            value: '8080'
          - name: NEW_RELIC_APP_NAME
            value: streams.anrop.se
          - name: NEW_RELIC_LICENSE_KEY
            valueFrom:
              secretKeyRef:
                name: newrelic
                key: licenseKey
          - name: TWITCH_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: twitch
                key: clientId
          - name: TWITCH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: twitch
                key: clientSecret
        ports:
          - containerPort: 8080
      restartPolicy: Always
