apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    run: api
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: public
  selector:
    run: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      run: api
  replicas: 1
  template:
    metadata:
      labels:
        run: api
    spec:
      containers:
      - name: api
        image: anrop/aar-go
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: postgres
                key: url
          - name: PORT
            value: '8080'
          - name: NEW_RELIC_APP_NAME
            value: api.aar.anrop.se
          - name: NEW_RELIC_LICENSE_KEY
            valueFrom:
              secretKeyRef:
                name: newrelic
                key: licenseKey
        ports:
          - containerPort: 8080
      restartPolicy: Always
