apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: worker
spec:
  schedule: "@daily"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: worker
            image: anrop/arma-workshop-missions-worker
            env:
              - name: DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: postgres
                    key: url
              - name: STEAM_WEB_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: steam
                    key: webApiKey
          restartPolicy: OnFailure
